name: Docker Image CI

on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crazled/playmaker:$(date +%s)
